### ISSUE TITLE
Invalid mysql database collation, expected utf8

### ISSUE THREAD

**Issue by nikitinsm** [berngp/docker-zabbix#14]
Seems to be the aim is utf8 database, but some reason it is latin instead.

**Comment by berngp** [comment]
@nikitinsm just pushed a [branch](https://github.com/berngp/docker-zabbix/tree/feature/14-UTF8) which forces the MySQL DB to UTF8. Need to test things out but feel free to give it a try.

**Comment by nikitinsm** [comment]
It still latin1 fields caused of the mysql dump I think not my.ini config

```
for t in $(mysql --user=zabbix --password=zabbix  --database=zabbix -e "show tables";);do echo "Altering" $t;mysql --user=zabbix --password=zabbix --database=zabbix -e "ALTER TABLE $t CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;";done
```

This solves problem you can add it after db dump is fully loaded

**Comment by berngp** [comment]
Thanks Sergey,
I'll follow you advice.
Cheers

**Comment by nikitinsm** [comment]
BTW I have installed zabbix directly (without docker) from deb and DB is utf-8
