### ISSUE TITLE
Communication with malicious IP

### ISSUE THREAD

**Issue by erikbotta** [berngp/docker-zabbix#28]
Hello friends,
 why this running image is communicating with 443 and 80 of 184.168.47.225 ??
Maltrail on our server is detecting this as threat. None of our host is configured to this IP. 
Any explanation?
Thx, Erik.
![snimek obrazovky 2016-01-13 v 1 24 16](https://cloud.githubusercontent.com/assets/832402/12281234/8e82965a-b994-11e5-9193-d0fff8eeb794.png)

**Comment by owlmsj** [comment]
Could you tell why this thread got closed? It was a misunderstanding?
